---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - labza-ca.yaml
  #- letsencrypt-prod-ca.yaml
  - cilium-crs.yaml
  - talos-etcd-defrag-cronjob.yaml
  - tekton-config.yaml
  # - mariadb-galera-prod.yaml
  - mariadb-prod.yaml
  - pgsql-prod.yaml
  - envoy-gateway.yaml
  - gateway-external.yaml
  - gateway-internal.yaml
  # - renovate.yaml