---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: keycloak-prod
spec:
  template:
    spec:
      containers:
        - name: keycloak
          env:
            # Production specific settings
            - name: KC_HOSTNAME
              value: "keycloak.${nginx_domain}"
            - name: KC_HOSTNAME_STRICT
              value: "true"