---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../apps/keycloak/base

# change namespace
namespace: keycloak-prod

# Update references
patches:
  # Update Ingress
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: keycloak.${nginx_domain}
      - op: replace
        path: /spec/tls/0/hosts/0
        value: keycloak.${nginx_domain}
    target:
      kind: Ingress
      name: prod-keycloak

  # Apply cluster-specific values
  - path: keycloak-values.yaml
    target:
      kind: StatefulSet
      name: keycloak