---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  values:
    cloudflare:
      ingress:
        - hostname: app.example.com
          service: http://servicename.namespace.svc
      secretName: cloudflaresecret
      tunnelName: example
    image:
      pullPolicy: IfNotPresent
      repository: docker.io/cloudflare/cloudflared
      tag: 2026.1.2
