---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snipe-it
  namespace: snipeit
spec:
  values:
    ingress:
      enabled: false
    podSecurityContext: 
      fsGroup: 50
    securityContext: 
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      runAsUser: 1000
      runAsGroup: 50
      seccompProfile:
        type: RuntimeDefault